apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "ingress"
spec:
  backend:
    serviceName: proxy-service
    servicePort: 80
