apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: demo-api-service
              servicePort: 80
          - path: /frontend
            backend:
              serviceName: demo-frontend-service
              servicePort: 80