apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-proxy-deployment
  labels:
    app: mym
    unit: proxy
spec:
  selector:
    matchLabels:
      app: mym
      unit: proxy
  template:
    metadata:
      labels:
        app: mym
        unit: proxy
    spec:
      containers:
        - name: proxy
          image: nuster/nuster:2.1.2.19-alpine
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config-volume
              readOnly: true
              mountPath: /etc/nuster/nuster.cfg
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: nuster-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-proxy-service
spec:
  type: NodePort
  selector:
    app: mym
    unit: proxy
  ports:
    - port: 80
      targetPort: 8080
