apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: mym
    unit: api
spec:
  selector:
    matchLabels:
      app: mym
      unit: api
  template:
    metadata:
      labels:
        app: mym
        unit: api
    spec:
      containers:
        - name: backend
          image: gcr.io/rosy-decker-240108/demo-api:1
          ports:
            - name: http
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: mym
    unit: api
  ports:
    - port: 80
      targetPort: 8000
